version: '3.8'
services:

  testconn:
    image: testconn:1.0
    container_name: testconn
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    stop_grace_period: 1m30s
